export const LOAD_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  OPEN: "OPEN",
  RESERVED: "RESERVED",
  BOOKED: "BOOKED",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
});

export const CLAIM_STATUS = Object.freeze({
  PENDING: "PENDING",
  WON_RESERVATION: "WON_RESERVATION",
  WAITLISTED: "WAITLISTED",
  PROMOTED: "PROMOTED",
  CONFIRMED: "CONFIRMED",
  EXPIRED: "EXPIRED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
  FAILED: "FAILED",
});

export const PUBLIC_LEAD_STATUS = Object.freeze({
  PRE_REGISTERED: "PRE_REGISTERED",
  QUEUED: "QUEUED",
  APPROVED: "APPROVED",
  CANCELLED: "CANCELLED",
});

export const ACTIVE_CLAIM_STATUSES = [
  CLAIM_STATUS.WON_RESERVATION,
  CLAIM_STATUS.WAITLISTED,
  CLAIM_STATUS.PROMOTED,
  CLAIM_STATUS.CONFIRMED,
];

export const WAITLIST_CLAIM_STATUSES = [CLAIM_STATUS.WAITLISTED];

export const RESERVATION_CLAIM_STATUSES = [CLAIM_STATUS.WON_RESERVATION, CLAIM_STATUS.PROMOTED];

export const TERMINAL_CLAIM_STATUSES = [
  CLAIM_STATUS.CONFIRMED,
  CLAIM_STATUS.EXPIRED,
  CLAIM_STATUS.REJECTED,
  CLAIM_STATUS.CANCELLED,
  CLAIM_STATUS.FAILED,
];

export const CLAIM_EVENT_TYPE = Object.freeze({
  CLAIM_CREATED: "CLAIM_CREATED",
  CLAIM_REJECTED: "CLAIM_REJECTED",
  CLAIM_WAITLISTED: "CLAIM_WAITLISTED",
  LOAD_RESERVED: "LOAD_RESERVED",
  CLAIM_PROMOTED: "CLAIM_PROMOTED",
  CLAIM_CONFIRMED: "CLAIM_CONFIRMED",
  CLAIM_CANCELLED: "CLAIM_CANCELLED",
  CLAIM_EXPIRED: "CLAIM_EXPIRED",
  LOAD_REOPENED: "LOAD_REOPENED",
  IDEMPOTENCY_REPLAY: "IDEMPOTENCY_REPLAY",
  WAITLIST_SKIPPED_INELIGIBLE: "WAITLIST_SKIPPED_INELIGIBLE",
  LOAD_UNAVAILABLE: "LOAD_UNAVAILABLE",
});

export const PUBLIC_LEAD_EVENT_TYPE = Object.freeze({
  PRE_REGISTERED: "PRE_REGISTERED",
  WHATSAPP_CLICKED: "WHATSAPP_CLICKED",
  QUEUED: "QUEUED",
  APPROVED: "APPROVED",
  CANCELLED: "CANCELLED",
});

export const IDEMPOTENCY_SCOPE = Object.freeze({
  CREATE_CLAIM: "load-claim:create",
  CONFIRM_CLAIM: "load-claim:confirm",
  CANCEL_CLAIM: "load-claim:cancel",
});
