export const DASHBOARD_SIDEBAR_COLLAPSED_WIDTH = 104;
export const DASHBOARD_SIDEBAR_EXPANDED_WIDTH = 340;
export const DASHBOARD_SIDEBAR_HORIZONTAL_INSET = 12;
export const DASHBOARD_SIDEBAR_EXPANDED_SHIFT =
  DASHBOARD_SIDEBAR_EXPANDED_WIDTH - DASHBOARD_SIDEBAR_COLLAPSED_WIDTH;

export const DASHBOARD_SIDEBAR_COLLAPSED_PANEL_WIDTH =
  DASHBOARD_SIDEBAR_COLLAPSED_WIDTH - DASHBOARD_SIDEBAR_HORIZONTAL_INSET * 2;
export const DASHBOARD_SIDEBAR_EXPANDED_PANEL_WIDTH =
  DASHBOARD_SIDEBAR_EXPANDED_WIDTH - DASHBOARD_SIDEBAR_HORIZONTAL_INSET * 2;

